package com.angga.submission;

import java.util.ArrayList;

public class PlayerData {
public static String[][] data = new String[][]{
        {"LeBron James", " Lahir 30 Desember, 1984) adalah pemain basket profesional asal Amerika yang bermain untuk Los Angeles Lakers dari National Basketball Association (NBA). James telah memenangkan 3 NBA championships (2012, 2013, 2016), 4 NBA Most Valuable Player Awards (2009, 2010, 2012, 2013), 3 NBA Finals MVP Awards (2012, 2013, 2016), 2 Olympic gold medals (2008, 2012), 1 NBA scoring title (2008), dan NBA Rookie of the Year Award (2004). Ia juga terpilih 12 kali dalam tim NBA All-Star (dinamai 2 kali MVP), 12 All-NBA teams, dan 6 All-Defensive teams, serta leading scorer Cavaliers sepanjang masa.", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/LeBron_James_%2815662939969%29.jpg/675px-LeBron_James_%2815662939969%29.jpg"},

        {"Stephen Curry", " Wardell Stephen Curry atau lebih dikenal sebagai Stephen Curry (lahir di Akron , 14 Maret 1988; umur 31 tahun) adalah pebasket profesional Amerika Serikat yang bermain sebagai point guard di klub Golden State Warriors di kompetisi NBA (National Basketball Association). Stephen Curry yang bertinggi badan 191 cm memiliki ball handling di atas rata-rata. Namanya dicatat dalam buku rekor NBA (termasuk wikipedia) sebagai salah satu pelempar 3 angka terbaik dalam sejarah bola basket. Pada musim 2014-2015, Ia memenangi NBA Most Valuable Player dan memimpin Golden State Warrior menjuarai NBA pertamanya sejak tahun 1975. Di musim NBA 2016-2017 Steph Curry membawa Golden State Warriors ke final NBA untuk ketiga kalinya secara beruntun dimana dia memenangi kompetisi NBA untuk kedua kalinya.", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Stephen_Curry_%2824180454343%29.jpg/900px-Stephen_Curry_%2824180454343%29.jpg"},

        {"Michael Jordan", " Michael Jeffrey Jordan (lahir di Brooklyn, New York, Amerika Serikat, 17 Februari 1963; umur 56 tahun) adalah pemain bola basket profesional asal Amerika. Ia merupakan pemain terkenal di dunia dalam cabang olahraga itu. Setidaknya, enam kali merebut kejuaraan NBA bersama kelompok Chicago Bulls (1991-1993, 1996-1998). Ia memiliki tinggi badan 198 cm dan merebut gelar pemain terbaik.", "https://upload.wikimedia.org/wikipedia/commons/c/c3/Jordan_by_Lipofsky_16577.jpg"},

        {"Russell Westbrook", " Russell Westbrook III (lahir long beach, California 12 November 1988) adalah pemain bola basket profesional berkebangsaan Amerika Serikat yang membela Houston rockets di kompetisi National Basketball Association (NBA). Dia terpilih NBA All-Star tujuh kali, dan dua kali sebagai Pemain NBA All-Star Game Most Valuable, memenangkan penghargaan berturut-turut pada tahun 2015 dan 2016. Ia juga merupakan anggota All-NBA Team enam kali dan memimpin liga dalam mencetak angka di musim kompetisi 2014-15 dan 2016-17. Pada 2017, Westbrook menjadi salah satu dari dua pemain dalam sejarah NBA dengan rata-rata triple-double selama satu musim, bersama dengan Oscar Robertson pada tahun 1962. Dia juga mencetak rekor untuk triple-doubles paling banyak dalam satu musim, dengan 42. Dia kemudian dinobatkan sebagai Pemain NBA Most Valuable Player 2016–17. Prestasi ini diulang pada musim berikutnya ketika dia kembali membuat triple-double di 80 pertandingan.", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Russell_Westbrook_%2832077032673%29.jpg/664px-Russell_Westbrook_%2832077032673%29.jpg"},

        {"James Harden", " James Edward Harden Jr. (Lahir di Los Angeles, California 26 Agustus 1989) adalah pemain bola basket profesional Amerika Serikat yang bermain di team Houston Rockets di kompetisi National Basketball Association (NBA). Harden bermain basket perguruan tinggi untuk Arizona State, di mana ia dinamakan Konsensus All-American dan Pac-10 Player of the Year pada 2009. Harden direkrut pada pilihan ketiga secara keseluruhan draft NBA tahun 2009 oleh Oklahoma City Thunder. Pada tahun 2012, ia dinobatkan sebagai NBA Sixth Man of the Year dengan Oklahoma City Thunder dan membantu team mencapai Final NBA 2012.[1]", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/James_Harden_%2830852408515%29.jpg/807px-James_Harden_%2830852408515%29.jpg"},

        {"Dirk Nowitzki", " Dirk Werner Nowitzki (lahir di Würzburg, Jerman Barat, 19 Juni 1978; umur 41 tahun) adalah pemain bola basket Jerman yang bermain di Amerika Serikat yang bermain dalam kompetisi National Basketball Association (NBA) dan di klub Dallas Mavericks. Dirk Nowitzki dipandang sebagai salah satu pemain asing terbesar dalam sejarah kompetisi bola basket NBA Bertinggi badan 213 cm, Nowitzki berposisi sebagai forward, Ia menunjukkan sesuatu yang unik pada saat berhadapan dengan pemain bertahan (defender) karena ia lebih tinggi dari kebanyakan pemain depan (small forward). Tetapi ia juga memiliki kemampuan menembak akurat untuk ukuran pemain tinggi besar seukurannya. Selama bertahun-tahun fadeaway jump shot-nya membuktikan sebagai salah satu manuver lemparan paling efektif dalam sejarah NBA.", "https://upload.wikimedia.org/wikipedia/commons/7/7c/DirkNowitzki.jpg"},

        {"Dwyane Wade", " Dwyane James Wade,Jr. lahir 17 Januari 1982 di Lakers, Illinois, Amerika James, adalah pemain bola bola basket bertinggi tubuh 193 cm dan berjuluk Flash atau D-Wade bermain di klub NBA Los Angeles Lakers sebagai guard. Setelah sukses karier di perguruan tinggi di Marquette, Wade di draft pilihan kelima secara keseluruhan pada NBA draft 2003 oleh Miami Heat. Pada musim ketiganya, Wade memimpin Miami Heat menjuarai NBA pertamanya dalam sejarah, dan dinamakan NBA Finals MVP 2006. Pada olimpiade musim panas 2008, Wade memimpin team basket Amerika James, yang dikenal sebagai Redeem Team, memimpin pencetak angka dan membantu mereka meraih medali emas. Pada musim kompetisi 2008-2009, Wade memimpin dalam mencetak angka di liga dan mendapatkan gelar pencetak angka NBA pertamanya. Dengan LeBron James dan Chris Bosh, Wade membantu Miami Heat mencapai NBA Finals keempat berturut-turut dari tahun 2011 hingga 2014, memenangkan kejuaraan berurutan pada tahun 2012 dan 2013. Setelah 1½ musim jauh dari Heat, bergabung dengan Lakers dan Lakers, Wade ditukar kembali ke Miami pada Februari 2018. Ia terpilih NBA All-Star 12 kali, Wade adalah pemimpin sepanjang masa dalam mencetak poin, permainan, assist dan steal, tembakan yang dilakukan (shot made) dan tembakan young man diambil (shot taken).", "https://upload.wikimedia.org/wikipedia/commons/b/bc/Dwyane_Wade.jpg"},

        {"Derrick Rose", " Derrick Martell Rose (lahir 4 Oktober 1988; umur 30 tahun) adalah pemain basket berkebangsaan Amerika dan bermain Warriors National Basketball Association (NBA). pada NBA Draft tahun 2008 dipilih oleh Chicago Bulls dan memulai karier cemerlangnya. Dia juga berperan dalam raihan Amerika serikat yang meraih medali emas di Piala Dunia Bola Basket.", "https://upload.wikimedia.org/wikipedia/commons/0/0d/Rose-20190120_%28cropped%29.jpg"},

        {"Klay Thompson", " Klay Alexander Thompson (lahir 8 Februari 1990) adalah pemain bola basket profesional Amerika Serikat yang bermain untuk Golden State Warriors di kompetisi National Basketball Association (NBA). Ia merupakan putra mantan pemain NBA Mychal Thompson, Ia bermain bola basket perguruan tinggi selama tiga musim di Washington State University, yang mana Ia dua kali team pertama seleksi semua konferensi di Pac-10.", "https://upload.wikimedia.org/wikipedia/commons/1/10/Klay_Thompson_in_2015.jpg"},

        {"Yao Ming", " Yao Ming (lahir di Shanghai, Tiongkok, 12 September 1980; umur 38 tahun), adalah mantan pemain bola basket asal Tiongkok pertama yang bermain di kompetisi NBA. Sejak pertama kali masuk NBA pada tahun 2002 hingga pensiun, dia bermain di klub Houston Rockets. Bersama Gheorghe Muresan, Manute Bol, dan Shawn Bradley ia menjadi pemain basket tertinggi di kompetisi NBA dengan tinggi tubuh mencapai 229 cm.", "https://upload.wikimedia.org/wikipedia/commons/a/a8/YaoMingonoffense2_crop.jpg"}
};
    public static ArrayList<Player> getListData(){
        ArrayList<Player> list = new ArrayList<>();
        for (String[] aData : data) {
            Player player = new Player();
            player.setName(aData[0]);
            player.setFrom(aData[1]);
            player.setFoto(aData[2]);
            list.add(player);
        }
        return list;
    }
}